"""empty message

Revision ID: 4ba8e800a4ca
Revises: 
Create Date: 2021-05-18 19:23:18.748462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba8e800a4ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_index(op.f('ix_empresa_cnpj'), 'empresa', ['cnpj'], unique=True)
    op.create_table('fornecedor',
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_fornecedor')
    )
    op.create_index(op.f('ix_fornecedor_cnpj'), 'fornecedor', ['cnpj'], unique=True)
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('idProduto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('kg', sa.Float(), nullable=True),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedor.id_fornecedor'], ),
    sa.PrimaryKeyConstraint('idProduto')
    )
    op.create_table('usuarioSistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('tipoUsuario', sa.String(length=50), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarioSistema_cpf'), 'usuarioSistema', ['cpf'], unique=True)
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('notaFiscal', sa.String(length=50), nullable=True),
    sa.Column('dataPedido', sa.Date(), nullable=True),
    sa.Column('prazoPagamento', sa.Integer(), nullable=True),
    sa.Column('statusPagamento', sa.Boolean(), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('id_empresa_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_funcionario'], ['usuarioSistema.id'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('itens_pedido',
    sa.Column('id_itens', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.idProduto'], ),
    sa.PrimaryKeyConstraint('id_itens')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_usuarioSistema_cpf'), table_name='usuarioSistema')
    op.drop_table('usuarioSistema')
    op.drop_table('produto')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_fornecedor_cnpj'), table_name='fornecedor')
    op.drop_table('fornecedor')
    op.drop_index(op.f('ix_empresa_cnpj'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
